// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.14.0
// source: calcpb/calc.proto

package calcpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AdditionArgs struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Arg []int32 `protobuf:"varint,1,rep,packed,name=arg,proto3" json:"arg,omitempty"`
}

func (x *AdditionArgs) Reset() {
	*x = AdditionArgs{}
	if protoimpl.UnsafeEnabled {
		mi := &file_calcpb_calc_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AdditionArgs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdditionArgs) ProtoMessage() {}

func (x *AdditionArgs) ProtoReflect() protoreflect.Message {
	mi := &file_calcpb_calc_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdditionArgs.ProtoReflect.Descriptor instead.
func (*AdditionArgs) Descriptor() ([]byte, []int) {
	return file_calcpb_calc_proto_rawDescGZIP(), []int{0}
}

func (x *AdditionArgs) GetArg() []int32 {
	if x != nil {
		return x.Arg
	}
	return nil
}

type CalcSumRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Args *AdditionArgs `protobuf:"bytes,1,opt,name=args,proto3" json:"args,omitempty"`
}

func (x *CalcSumRequest) Reset() {
	*x = CalcSumRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_calcpb_calc_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CalcSumRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalcSumRequest) ProtoMessage() {}

func (x *CalcSumRequest) ProtoReflect() protoreflect.Message {
	mi := &file_calcpb_calc_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalcSumRequest.ProtoReflect.Descriptor instead.
func (*CalcSumRequest) Descriptor() ([]byte, []int) {
	return file_calcpb_calc_proto_rawDescGZIP(), []int{1}
}

func (x *CalcSumRequest) GetArgs() *AdditionArgs {
	if x != nil {
		return x.Args
	}
	return nil
}

type CalcSumResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sum int32 `protobuf:"varint,1,opt,name=sum,proto3" json:"sum,omitempty"`
}

func (x *CalcSumResponse) Reset() {
	*x = CalcSumResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_calcpb_calc_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CalcSumResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalcSumResponse) ProtoMessage() {}

func (x *CalcSumResponse) ProtoReflect() protoreflect.Message {
	mi := &file_calcpb_calc_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalcSumResponse.ProtoReflect.Descriptor instead.
func (*CalcSumResponse) Descriptor() ([]byte, []int) {
	return file_calcpb_calc_proto_rawDescGZIP(), []int{2}
}

func (x *CalcSumResponse) GetSum() int32 {
	if x != nil {
		return x.Sum
	}
	return 0
}

var File_calcpb_calc_proto protoreflect.FileDescriptor

var file_calcpb_calc_proto_rawDesc = []byte{
	0x0a, 0x11, 0x63, 0x61, 0x6c, 0x63, 0x70, 0x62, 0x2f, 0x63, 0x61, 0x6c, 0x63, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x04, 0x63, 0x61, 0x6c, 0x63, 0x22, 0x20, 0x0a, 0x0c, 0x41, 0x64, 0x64,
	0x69, 0x74, 0x69, 0x6f, 0x6e, 0x41, 0x72, 0x67, 0x73, 0x12, 0x10, 0x0a, 0x03, 0x61, 0x72, 0x67,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x05, 0x52, 0x03, 0x61, 0x72, 0x67, 0x22, 0x38, 0x0a, 0x0e, 0x43,
	0x61, 0x6c, 0x63, 0x53, 0x75, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x26, 0x0a,
	0x04, 0x61, 0x72, 0x67, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x63, 0x61,
	0x6c, 0x63, 0x2e, 0x41, 0x64, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x41, 0x72, 0x67, 0x73, 0x52,
	0x04, 0x61, 0x72, 0x67, 0x73, 0x22, 0x23, 0x0a, 0x0f, 0x43, 0x61, 0x6c, 0x63, 0x53, 0x75, 0x6d,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x73, 0x75, 0x6d, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x73, 0x75, 0x6d, 0x32, 0x4d, 0x0a, 0x11, 0x43, 0x61,
	0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x6f, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12,
	0x38, 0x0a, 0x07, 0x43, 0x61, 0x6c, 0x63, 0x53, 0x75, 0x6d, 0x12, 0x14, 0x2e, 0x63, 0x61, 0x6c,
	0x63, 0x2e, 0x43, 0x61, 0x6c, 0x63, 0x53, 0x75, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x15, 0x2e, 0x63, 0x61, 0x6c, 0x63, 0x2e, 0x43, 0x61, 0x6c, 0x63, 0x53, 0x75, 0x6d, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x08, 0x5a, 0x06, 0x63, 0x61, 0x6c,
	0x63, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_calcpb_calc_proto_rawDescOnce sync.Once
	file_calcpb_calc_proto_rawDescData = file_calcpb_calc_proto_rawDesc
)

func file_calcpb_calc_proto_rawDescGZIP() []byte {
	file_calcpb_calc_proto_rawDescOnce.Do(func() {
		file_calcpb_calc_proto_rawDescData = protoimpl.X.CompressGZIP(file_calcpb_calc_proto_rawDescData)
	})
	return file_calcpb_calc_proto_rawDescData
}

var file_calcpb_calc_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_calcpb_calc_proto_goTypes = []interface{}{
	(*AdditionArgs)(nil),    // 0: calc.AdditionArgs
	(*CalcSumRequest)(nil),  // 1: calc.CalcSumRequest
	(*CalcSumResponse)(nil), // 2: calc.CalcSumResponse
}
var file_calcpb_calc_proto_depIdxs = []int32{
	0, // 0: calc.CalcSumRequest.args:type_name -> calc.AdditionArgs
	1, // 1: calc.CalculatorService.CalcSum:input_type -> calc.CalcSumRequest
	2, // 2: calc.CalculatorService.CalcSum:output_type -> calc.CalcSumResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_calcpb_calc_proto_init() }
func file_calcpb_calc_proto_init() {
	if File_calcpb_calc_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_calcpb_calc_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AdditionArgs); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_calcpb_calc_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CalcSumRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_calcpb_calc_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CalcSumResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_calcpb_calc_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_calcpb_calc_proto_goTypes,
		DependencyIndexes: file_calcpb_calc_proto_depIdxs,
		MessageInfos:      file_calcpb_calc_proto_msgTypes,
	}.Build()
	File_calcpb_calc_proto = out.File
	file_calcpb_calc_proto_rawDesc = nil
	file_calcpb_calc_proto_goTypes = nil
	file_calcpb_calc_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// CalculatorServiceClient is the client API for CalculatorService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CalculatorServiceClient interface {
	CalcSum(ctx context.Context, in *CalcSumRequest, opts ...grpc.CallOption) (*CalcSumResponse, error)
}

type calculatorServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCalculatorServiceClient(cc grpc.ClientConnInterface) CalculatorServiceClient {
	return &calculatorServiceClient{cc}
}

func (c *calculatorServiceClient) CalcSum(ctx context.Context, in *CalcSumRequest, opts ...grpc.CallOption) (*CalcSumResponse, error) {
	out := new(CalcSumResponse)
	err := c.cc.Invoke(ctx, "/calc.CalculatorService/CalcSum", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CalculatorServiceServer is the server API for CalculatorService service.
type CalculatorServiceServer interface {
	CalcSum(context.Context, *CalcSumRequest) (*CalcSumResponse, error)
}

// UnimplementedCalculatorServiceServer can be embedded to have forward compatible implementations.
type UnimplementedCalculatorServiceServer struct {
}

func (*UnimplementedCalculatorServiceServer) CalcSum(context.Context, *CalcSumRequest) (*CalcSumResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CalcSum not implemented")
}

func RegisterCalculatorServiceServer(s *grpc.Server, srv CalculatorServiceServer) {
	s.RegisterService(&_CalculatorService_serviceDesc, srv)
}

func _CalculatorService_CalcSum_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CalcSumRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CalculatorServiceServer).CalcSum(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/calc.CalculatorService/CalcSum",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CalculatorServiceServer).CalcSum(ctx, req.(*CalcSumRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _CalculatorService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "calc.CalculatorService",
	HandlerType: (*CalculatorServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CalcSum",
			Handler:    _CalculatorService_CalcSum_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "calcpb/calc.proto",
}
